name: Flutter CI

on:
  push:
    branches:
      - main
      - features/*
  pull_request:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug

      - name: Build AppBundle
        run: flutter build appbundle --debug
